### PR TITLE
nvme-cli: version bump to 1.5

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by oxc** [comment]
Sorry about that. I remembered seeing the pull request, but thought it was on Gerrit and had vanished with it. Thanks!

**Comment by Cogitri** [comment]
Don't worry about it :)

Maybe you do want to migrate your repository to gitlab.exherbo.org though

**Comment by oxc** [comment]
The repository is mirrored in g.e.o, you can create pull request there as well.

**Comment by Cogitri** [comment]
Oh, didn't check that beforehand :)

**Comment by oxc** [comment]
Dont worry, it didn't exist when you created this pull request :)

**Pull request closed without merging**
